### ISSUE TITLE
syntax error on Node v4 (LTS)

### ISSUE THREAD

**Issue by sintaxi** [zeit/list#24]
heya ▲! `list` seems to be returning a SyntaxError with node `v4.4.0`.

```
/usr/local/lib/node_modules/list/dist/bin/list:220
    const { pathname } = (0, _url.parse)(req.url);
          ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
```
cheers.

**Comment by leo** [comment]
Hey! 😊 Node v6 (latest) is needed, if you want to run `list` (same with all of our major packages):

https://github.com/zeit/list#usage

**Comment by sintaxi** [comment]
Apologies. Next time I'll RTFM 😸.
